# Generated by Django 5.0.2 on 2025-12-04 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_movil_escolar_api', '0004_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=3)),
                ('dias_json', models.TextField(blank=True, default='[]', null=True)),
                ('hora_i', models.TimeField()),
                ('hora_f', models.TimeField()),
                ('salon', models.CharField(max_length=15)),
                ('programa', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('profesor_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web_movil_escolar_api.maestros')),
            ],
        ),
    ]
