# Generated by Django 5.0.2 on 2025-12-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_movil_escolar_api', '0005_materias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias',
            old_name='profesor_id',
            new_name='profesor',
        ),
    ]
